on: [push]
name: Azure Deploy PR Environment

env:
  IMAGE_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}/weather-api:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/api
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t $IMAGE_NAME
        docker push $IMAGE_NAME

  build-and-deploy-infra:
    needs:
      - build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./src/bicep/main.bicep
        parameters: envName=${{ github.run_number }} containerImage=${{ env.IMAGE_NAME }} containerPort=80 registryServer=${{ secrets.REGISTRY_SHORT_NAME }} registryUsername=${{ secrets.REGISTRY_USERNAME }} registryPassword=${{ secrets.REGISTRY_PASSWORD }} registryResourceGroup=${{ secrets.REGISTRY_AZURE_RG }}
        failOnStdErr: false